### ISSUE TITLE
Int64 encoded as string

### ISSUE THREAD

**Issue by dbrattli** [thoth-org/Thoth.Json.Net#16]
Currently, Thoth encodes `int64` as a string i.e:
```fs
(Encode.list [ Encode.int64 42L ] |> Encode.toString 0) = "[\"42\"]"
```

Which might not be what you expect, and most importantly it might not be what the receiver expect. Int64 allows values up to 9223372036854775807 while JSON safe numbers are up to 9007199254740991. JValue will accept `Int64.MaxValue`, so not sure why we encode them as string? I would suggest that we encode `int64` directly using `JValue(value) :> JsonValue` and instead document that numbers above 9007199254740991 might be unsafe for the receiver? At least i think it's safer than sending strings by default, or?

**Comment by MangelMaxime** [comment]
I don't see any problem with using string to represent `int64` in JSON. Because JSON doesn't know `int64` type then we have to model our own representation. I prefer to have full range support of `int64` than partial which could lead to subtle bugs.

In the past, we had a similar problem when working with GUID. For example, Fable was only supporting a subset of GUID and while the compiler was saying everything is fine then at runtime we had errors. At the time, we decided to ensure full support of the GUID otherwise it would make that type unstable and so unusable.

I am closing because I don't think something will change but if you want to continue the discussion please do :)
