### ISSUE TITLE
Question - Case insensitive decode

### ISSUE THREAD

**Issue by marto83** [thoth-org/Thoth.Json.Net#36]
I'm trying to parse a json object where the properties come from two different systems which have different fields with different case. 

Here is a sample
system1:
`[
     {"id": "39336bd7-ecdc-4755-ac21-8f852d70d311", "data": ["one", "two", "three", "four"], "userid": "user22", "deviceid": "device123", "timestamp": 2345} ]`

system2:
`[
     {"id": "39336bd7-ecdc-4755-ac21-8f852d70d312", "data": ["one", "two" ], "userId": "user122", "deviceId": "device123", "timestamp": 2346} ]`

Have a look at `userId` and `deviceId`

Here is my decoder: 

    Decode.object
                        (fun get ->
                              {
                                  Id = get.Required.Field "id" Decode.guid
                                  Data = get.Required.Field "data" JObjectDecoder
                                  DeviceId = get.Required.Field "deviceid" Decode.string
                                  Timestamp = get.Required.Field "timestamp" Decode.int64
                                  UserId = get.Required.Field "userid" Decode.string
                              }
                        )

How can I get it to support both cases?

**Comment by MangelMaxime** [comment]
Hello,

Out of the box the solution would be to use `Decode.oneOf` to handle both possible case:

**`Decode.oneOf` with `Decode.object`**

```fs
    static member Decoder =
        Decode.oneOf [
            Decode.object
                (fun get ->
                    {
                        Id = get.Required.Field "id" Decode.guid
                        Data = get.Required.Field "data" (Decode.list Decode.string)
                        DeviceId = get.Required.Field "deviceid" Decode.string
                        Timestamp = get.Required.Field "timestamp" Decode.int64
                        UserId = get.Required.Field "userid" Decode.string
                    }
                )

            Decode.object
                (fun get ->
                    {
                        Id = get.Required.Field "id" Decode.guid
                        Data = get.Required.Field "data" (Decode.list Decode.string)
                        DeviceId = get.Required.Field "deviceId" Decode.string
                        Timestamp = get.Required.Field "timestamp" Decode.int64
                        UserId = get.Required.Field "userId" Decode.string
                    }
                )
        ]
```

You can also use `Decode.mapX` to reduve a bit the redundant code:

**`Decode.oneOf` with `Decode.map5`**

```fs
    static member Decoder2 =
        let deviceIdDecoder =
            Decode.oneOf [
                Decode.field "deviceId" Decode.string                   
                Decode.field "deviceid" Decode.string
            ]

        let userIdDecoder =
            Decode.oneOf [
                Decode.field "userId" Decode.string                   
                Decode.field "userid" Decode.string
            ]

        Decode.map5 (fun id data deviceId timestamp userId ->
            {
                Id = id
                Data = data
                DeviceId = deviceId
                Timestamp = timestamp
                UserId = userId
            }
        )
            (Decode.field "id" Decode.guid)
            (Decode.field "data" (Decode.list Decode.string))
            deviceIdDecoder
            (Decode.field "timestamp" Decode.int64)
            userIdDecoder
```

A cleaner solution would be to implement your own version of `Decode.object` or `Decode.field` which are case-insensitive.

ℹ️ The implementation is done using Thoth.Json and not Thoth.Json.Net because it was easier for me for providing a real live example. The logic is exactly the same, you just need to adapt for Newtonsoft APIs.

```fs
// Partially copied from Thoth.Json 
module internal Helpers =
    [<Emit("typeof $0")>]
    let jsTypeof (_ : JsonValue) : string = jsNative

    let inline getField (fieldName: string) (o: JsonValue) = o?(fieldName)

    [<Emit("$0 === null ? false : (Object.getPrototypeOf($0 || false) === Object.prototype)")>]
    let isObject (_ : JsonValue) : bool = jsNative

    [<Emit("Object.keys($0)")>]
    let keys (_ : JsonValue) : string array = jsNative

    let isUndefined (o: JsonValue): bool = jsTypeof o = "undefined"
    
module Decode =

    let caseInsensitiveField (fieldName: string) (decoder : Decoder<'value>) : Decoder<'value> =
        fun path value ->
            if Helpers.isObject value then
                let realFieldName =
                    value
                    |> Helpers.keys
                    |> Array.tryFind (fun name ->
                        name.ToLower() = fieldName.ToLower()
                    )

                match realFieldName with
                | Some realFieldName ->
                    let fieldValue = Helpers.getField realFieldName value
                    if Helpers.isUndefined fieldValue then
                        Error(path, BadField ("an object with a field named `" + fieldName + "` (case insensitive)", value))
                    else
                        decoder (path + "." + fieldName) fieldValue

                | None ->
                    Error(path, BadField ("an object with a field named `" + fieldName + "` (case insensitive)", value))

            else
                Error(path, BadType("an object", value))
```

Usage:

```fs
    static member Decoder3 =
        // I don't use Decode.object as an example because I would have to re-implement it entirely
        // But you could create your own Decode.insensitiveObject
        Decode.map5 (fun id data deviceId timestamp userId ->
            {
                Id = id
                Data = data
                DeviceId = deviceId
                Timestamp = timestamp
                UserId = userId
            }
        )
            (Decode.caseInsensitiveField "id" Decode.guid)
            (Decode.caseInsensitiveField "data" (Decode.list Decode.string))
            (Decode.caseInsensitiveField "deviceId" Decode.string)
            (Decode.caseInsensitiveField "timestamp" Decode.int64)
            (Decode.caseInsensitiveField "userId" Decode.string)
```

[REPL demo](https://fable.io/repl/#?code=PYBwpgdgBAKgFsALnAdAKQM7AgWAFCiRQBiAhgEYA2YKAwsAE5j6HRlU31PoYCSEiMA1D581RFABWWCAEYoAXnxQVUAEQaA2lADeagJYATNQC51AZgCc58wDZyhgOwBaMAGNDb5wBZHAVj9nUjcAJllnAA4AMwi-EKcABkNzWRC1ABp1Q1JEUlMoTTVsMAz1RAB3YDUoAF1MtQBXDCFeYzNG5oZUtPrDMAA3fTcwVvy1PsHh1PNStUR9AFswDFyFkHyQ829bAF9ajTVRPHEpGRDFZVUD7T0jMasbeydXDy9fAKDQ8OjY+McklKyWbZXL5QrFWYVKr1ZBMEr1KLABoMNR1dRNIR3doYhghHpZAZDMBYgmTMDTSGLZardZmTbePx7GoHI74AD0bKgAAVSAx5qRKJQAJ5QNygfRgQxQKLCBawBDIHjYKD4BbAQwNahQfQCIQQAVQAASYEo4AYGAueFUBQAPABRBb6RAACjmQvAwCiUAAJAk1ABKAB8NUuKhO0hg7rAnqgzoA+lAzJhsAA1AUNMD+xNQFYMHUAc0UpwAcjl9P1mHhQ1ATjrKDqwFB82BEMQJZQpc6ou3DKWlmZcwWs87gEmZGnKBmswooMAAPxdnt9zNHa2ae2Ol1qX2KBQziCayhQOfSgXNbPOgDy5Ek7kQKGbiC5wkQSCjl6izp3AB9v6fKM0057lA163m494gC+b7gP6AbBtWtYYKBd6xgmY6pummbZuQwDAEeM7SKW8wVquqjrg6Tqush4EoAA1mAQoYF+CSwUGIZWqoJz0YxqHZsmEATlO2aDhAha8gwpAigRGBEeWlYIS22oYAAqhAfTdhAkqxqOUD8YJmZmDheFFhGUYxsARaNGpYAaZKhwcSoqrqpqjYACLuOqjZKFWDk1opbikM0-DNBAGBOnJbYmp23ZRcuA6IHmonDn0Yp9Aw2bualQg2gA5P0mGBlmZiZZ5DC5flk5gIGlrWtaUQNNAIA5HAUAVRmUDOIG1a1ao+hesappCBgKD6EhN4oW1jbIJA3U9bVJxMAKkUdsuNVzet1qTbNG21d+1UDWaw3cRg207aoe1QAAggwElCigCVCm2amxvV0D6ksHVdb5Z0be9NAwMAAAywDlEIzrTtKS6kEsKAA8DoMMODp0-f6pE-SoCw5G4LWLZQy29tDjblE6cDI3Nf4AMrAB9uP46tnVkztJwxR2+lFgdQ0Pi2+NQLTUMfVt33oyofVGiah0jSp1m2VKLOGGz024ELwvWnaN2MM6TXIJkABCpCGDzrqkNAwDjeBUDE8gUCkJDUVQH9UoAAbVAA1LbK2E1AbtqI7sYBeeOohWFxGZqUk3+qjyvoyazSM+jKWlbGWstd7KCu+7BNLFmcv6Wj6N-sWxSfXH61q8IiPJ7r+uG2oxuzmbEiWy1Nty-bhNO+ncurd7vvOv7jaB5AwdybBmTh5Hccx5WKtQGXGuV1AeuGJG4BGybDdh5hEdHIgUZQMpnRrSoOina02YU4xggLCgADiDRGKdrk5Db8WJYW9YrI-hLDGfr8FqdMAqQrGhiAbMOpEC2G8KdA+LQpR-1EiqXyOw87APmG4KASwFjkCEFAEqaUj61TwTQYoH4ChxyISgU2YFEAl1UF2BqTZFIMyjj9E+LCVZnxnI+FAAAlMAABHe+TBDAoB5gYYwuCPJ9AfPfQwtCdpP1yEWbhfDBH6GEaInsWRn7VGdBQj+EgKEiXzJHGe613Jkk4Yw+8qihGSk0XbcY39iQSKMQlf+7DhaAKWMAtYyiWy8IEXYkRYj5g+JpNUCh4DIHyI2jAhgViVFBPUfYsROI7iSKyigYxsTrTIM8bVCeBSKFULvLE+h0BHzFwKetNhZi5qJICbYlJIStHiMiVImg+ZZG5Lmoom2XCmnJI0WIkEeRYz6NGoYzp2T3FJV6T1CxRJGk2OGaktpExlmuJmTkmpZ1vHUhAf41ZaiRltLCYctYHSsnRKgXsna8SVmBNOesxxOJRiZM8rMt+CyoD5JnqYua7FrTVlQUMDBYAsE4KIbiAh1oTibJ-oYGFcK+kzJIV6TQsSKGtycZY7ZWTjH1MQTPHFGznEZLcT8gp7FTonHecizp6VvI-RKZpUhWL7mfOkbihl1yvlEvqdimZvLOiUp2XM-McdaVRwoZjEAfgXoMKMFAMZqrnFnwub40BDLqmsNiVYh+XL+lFjGcK-FpqNVyK5Qc7VRYtU0liY8qUM4GVx3+XNQFO09EiraeKrJ3SjBeo2j6rJuKxm6MmSsblNBjHbwKYikYjKsoMDjqGr5uKHUgP5dI25wb1oMphSg3IaCIVQvSjC8wqKVAcigLwVV2AcoSAxDGyhDdrYWjrmAAAHiArU2CAotvrZUTUUo4CkArFAV8vMwDOEWCAagSwBDagkJAeYTBhSnVrTrBoEghRIlFEiDsopFqCCgPu5Es5yjQCiaFIe4UKzURobKmZ8rFUVO1FKNVibNVAJpFAXVzD9VcsNda0lz9TXP3NVsy1+LYm2v-TOLNawnWdCsW6gpHqer5rmum6R-dgr3pDmI-1XzA2GBwz1PDNACN3tCg+sAoydETJmQY1tcbKO1WoygWjQcGOjKtTm2NkrOPWm47xojEVzl-uza2vNaaKESfo8RtpfL2MibziCvAaAKY8ewFgagKBKDAHzNxhqGBSBREY7KCmkqWNZLY-ElAMKszSGwLISOOm9OhTwjQYzpmKHmcs9Z6mtm372a+Y5zozmmWubOEUrzYofOGf82Z0KwXiA2bs9xqLQgYsppCHF9znndNJYM35kzaWLNWcy6F7LUaJBOZhYV042BCtHES-p3zRnKuBfSzVrL4WctTP3tFytRW5Ale8+VnrAWZlBYG3VobDXRt5fG61iAhWgA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwssOYLona6pMJl3aJTAEQB9TwAkA8gDKAt5KUHQARrpK2qgSYAB0pNocaDRxdNzxEHRc8QBWuu4wwEq29o5W2DZ2Dk4ubl6+gcGeoRFRMShx5GgcEInJqemZ2bkFRSVltZWYiFOOzq4eJKS6AFxKSjRcpADWAObxUhBKAAIA7kjhx6TcfGBRl9d9t1z3ugWnAEzxAAzxAGYlBIaLowH1KFAkPgeLpKLoAKzkdAoRxIbT5QrFUo1CpzXF1JbuFbrTbbPaHY5nJ43O6w4Gg8EQSHQ96nACM8R+vwZYIhSChMIeWRymImOPKYHg1UliwaJI2Wx2ByOfWpV1pb3pui0aCEvQgHPinKBOvQ+r6IrGWMmBPgCBKIFQGAd4RSQkkUBQul0HlRFCkPBQOXRRTgOFwECE5HCRnBXEwXvCAo8HA44qjMbj3GlSjdevtjsgsDgQA&css=BYFwtgNgNAUARgewCYE8AEBvGadoGYIB2IAtAM4CWAXgKYBcaAjAGwAOAHgNwwC+MMAOjABDCoRIBjIiFGEaAJ0zZcSCmVYRhKBngg0uynAHcKSEMAaMADFYCk3XGmA0KAc1CWb9w2gBWAVzIQCjwUSWkaYgYJSJAFB1xhCDdxCjiwMmjY+J9dfRJVeRoJYKJohAh-MEJuPkExVn8QJUdWYSRVQlcGAQAmAFYisAScAmJyanomNgNHEzMLNAGrDhG0EXlXMRJEEBAEMEsh2pggA)

You are not the first one with a JSON where the properties name is case insensitive. The first person was having problem using the Auto module and because I agree to add support for it in Auto decoders I should probably include a case insensitive version for the different manual decoders.

Please note, that case insensitive version will be less performant because it needs to iterate over the properties name until it finds one that matches or none.

**Comment by marto83** [comment]
@MangelMaxime thanks for the detailed examples and the fast response.
