### ISSUE TITLE
Add auto-encoder/auto-decoder for Int64

### ISSUE THREAD

**Issue by forki** [thoth-org/Thoth.Json.Net#37]
That would be very helpful

**Comment by MangelMaxime** [comment]
Hello, it already exists but is not active by default because it increased too much the bundle size for Fable.

https://thoth-org.github.io/Thoth.Json/#Decoding-int64-decimal-or-bigint

**Comment by forki** [comment]
why would int64 increase the size? Isn't that just normal integer as seen from json?

**Comment by MangelMaxime** [comment]
Because int64 doesn't exist in JavaScript so Fable uses a custom type for it.

![image](https://user-images.githubusercontent.com/4760796/90409012-e9365100-e0a8-11ea-8551-276ae0d2d61c.png)

We prefer to not include it by default as it would increase the bundle size for everyone even if they don't use int64 types.
