### ISSUE TITLE
Fable 4 Support

### ISSUE THREAD

**Issue by panmona** [thoth-org/Thoth.Json.Net#51]
I'd like to upgrade a Fable project from Fable 3 to Fable 4. 
This package currently requires Fable.Core >= 3.1.6 and < 4.0. Which makes it not possible to upgrade to Fable 4.

I'm wondering the following:
- Why does this package have a dependency on Fable.Core?
- Can we lift the requirement that the Fable.Core version has to be lower than Fable 4?

**Comment by MangelMaxime** [comment]
Hello,

this project as a dependency on Fable.Core because we need access to `StringEnum` attribut to detect such decorated types and handle them correctly.

https://github.com/thoth-org/Thoth.Json.Net/blob/f449efee3af0de0c9a7bf460104d3009ef1c3be1/src/Types.fs#L72-L77

A new version has been released allowing usage of Fable.Core => 3 so this should allow both Fable.Core 3 and Fable.Core 4.
