### ISSUE TITLE
Question: How to reference both NuGet packages?

### ISSUE THREAD

**Issue by goswinr** [thoth-org/Thoth.Json.Net#59]
How to reference both NuGet packages ?
My library should work on .NET and JS in the fsproj I have: 
```xml
  <ItemGroup Condition="$(DefineConstants.Contains('FABLE_COMPILER'))">
    <PackageReference Include="Thoth.Json" Version="10.2.0" />
  </ItemGroup>

  <!-- a Not-Contains-Condition with leading exclamation mark:  -->
  <ItemGroup Condition="!$(DefineConstants.Contains('FABLE_COMPILER'))">
    <PackageReference Include="Thoth.Json.Net" Version="11.0.0" />
  </ItemGroup>
```
Is there another way to reference both packages?

then in the code : 
``` fsharp
#if FABLE_COMPILER
    open Thoth.Json
#else
    open Thoth.Json.Net
#endif

    Encode.Auto.toString(..)
```
When compiled with Fable 4.14 fails with
`The value, namespace, type or module 'Encode' is not defined. (code 39)`

**Comment by MangelMaxime** [comment]
Hello,

Do you need to use the Auto API or the manual API is enough?

If the manual API is enough, you could use:

- Thoth.Json.Core : To include only in the shared project as this is runtime agnostic
- Thoth.Json.JavaScript: To include only on the Fable project
- Thoth.Json.Newtonsoft: To include only on the .NET project

There package are a major rewrite of Thoth.Json to make it runtime agnostics (there is even a Python one) but I didn't announce it officially yet.

Usage:

```fs
// In the Core library
module MyLib

open Thoth.Json.Core

let value =
	Encode.string "maxime"

// In the runtime project
open Thoth.Json.JavaScript
// or 
// open Thoth.Json.Newtonsoft

let json =
	Encode.toSring 0 MyLib.value 
```

---

For the old packages, the error you are getting from Fable compilation is probably because Fable doesn't evaluate MSBuild condition. We have an experimental Project cracker which use MSBuild under the hood, which can be invoked by running `dotnet fable --test:MSBuildCracker` (it is possible that you need to delete your `obj` / `bin` folders to start from a clean state).

It is also possible to do:

``` xml
  <ItemGroup>
    <PackageReference Include="Thoth.Json" Version="10.2.0" />
  </ItemGroup>

  <!-- a Not-Contains-Condition with leading exclamation mark:  -->
  <ItemGroup Condition="!$(DefineConstants.Contains('FABLE_COMPILER'))">
    <PackageReference Include="Thoth.Json.Net" Version="11.0.0" />
  </ItemGroup>
```

as for .NET it will be harmless has long as you use:

```fs
#if FABLE_COMPILER
    open Thoth.Json
#else
    open Thoth.Json.Net
#endif
```

`Thoth.Json` will be included in your project but not used. It is not perfect but should do the jobs.

**Comment by goswinr** [comment]
Thanks, Maxime, I did not know about Thoth.Json.JavaScript.
I would like to use mostly the Auto API.
Using `--test:MSBuildCracker` it works with MS Build conditions !
Alternatively, just removing all conditions also works. (But has less compile safety.)
Thanks for your fast reply.

**Comment by MangelMaxime** [comment]
Auto API is planned for the new split library but I don't have an estimate for it yet focusing on Glutinum ATM.

Glad that we have a solution for your problem.

**Comment by goswinr** [comment]
Yes , if Glutinum works well it will be a Gamechanger!
