### ISSUE TITLE
2.5 -> 3.0 can encode less objects automatically

### ISSUE THREAD

**Issue by 0x53A** [thoth-org/Thoth.Json.Net#9]
I use thoth.json.net as the default json encoder, because that's how the safe template was structured:

https://github.com/SAFE-Stack/SAFE-BookStore/blob/master/src/Server/Program.fs#L45

With 2.5, everything worked fine.

Now I've updated to 3.0, and have two issues:

1) it can't serialize C# POCOs
2) It can no longer serialize records containing interfaces, even when wrapped in an option, and the actual value is none.

In both cases, the error message is ``Cannot generate auto encoder for MyType. Please pass an extra encoder.``

----------

For 1), this only kinda accidentally uses Thoth because it's registered as the default, it is actually used for an web api that is consumed by a C# client, and not for fable interop.

2) is used in Fable interop, here is a related issue on the client side: https://github.com/MangelMaxime/Thoth/issues/132#issuecomment-473804383

-----------

What is your opinion on this?

Is registering thoth as the default asp.net core serializer actually a good idea, or should I change this back to newtonsoft?

And for 2, would you be open to fixing this so it supports ``interface options``, as long as they are ``None``?

**Comment by MangelMaxime** [comment]
Which version of Thoth.Json.Net are you using?

Because version `3.1` was released a few day before to address the issue n°2.

> 
> ## 3.1.0 - 2019-05-03
> ### Fixed
> 
> * Fix auto encoder when generating an optinal unkown type and the runtime value is `None`

------------------------------------

About your issue n°1 -  C# POCOs

I wasn't even aware that the previous version was able to do it 🤷‍♂ . Perhaps, we can re-add support for it. I am not sure why it was supported before. It will mostly depends on what is needed to detect the POCOs case I think.

Would you be able to set up a minimal repro project? Do you have a minimal repro project for the POCOs?

**Comment by 0x53A** [comment]
> Which version of Thoth.Json.Net are you using?
Because version 3.1 was released a few day before to address the issue n°2.

``3.0``. I did a paket update on friday, probably missed 3.1 by a few hours, and so didn't think to check for an update again today. Will update, thanks!

-------------

> Would you be able to set up a minimal repro project? Do you have a minimal repro project for the POCOs?

I'll shortly add a complete repro project, but it's really just


```c#
    /// (the attributes are irrelevant and can be ignored)
    [DataContract]
    public class WcfAutoConfigResponse
    {
        ///
        [DataMember]
        public string FullUrl { get; set; }
        ///
        [DataMember]
        public string CertificateSubject { get; set; }
        ///
        [DataMember]
        public string UserName { get; set; }
        ///
        [DataMember]
        public string Environment { get; set; }
        ///
        [DataMember]
        public string ServiceName { get; set; }
        ///
        [DataMember]
        public string HostName { get; set; }
        ///
        [DataMember]
        public int Port { get; set; }
    }
```

```f#
// register default serializer
services.AddSingleton<IJsonSerializer>(ThothSerializer()) |> ignore

let wcfAutoConfig : WcfAutoConfigResponse = // ...

// saturn handler
get "/_Internal/WcfClientConfig" (fun next ctx -> json wcfAutoConfig next ctx)
```

**Comment by 0x53A** [comment]
Ok updating from 3.0 to 3.1 fixed issue n°2, thank you!

For issue n°1 I have create a repro here: https://github.com/0x53A/thoth-org-Thoth.Json.Net-issues-9

https://github.com/0x53A/thoth-org-Thoth.Json.Net-issues-9/blob/ea2698f983e9b0727208a38ed20f29834d59b633/ThothJsonWebApi/Startup.fs#L28-L41

The app works when i remove ``services.AddSingleton<IJsonSerializer>(ThothSerializer()) |> ignore`` and breaks with it.

**Comment by MangelMaxime** [comment]
Happy that the issue was indeed solved in 3.1.

Thank you for reproduction code. I asked for it because I not really an expert in .NET I am spending 95% of my time with JavaScript runtime ^^.

At least like that, I can try to take a look at it and see if I have an idea on how to support C# POCO. And add them to the tests etc. :)

**Comment by darting** [comment]
I have same issue with the issue 1 since my project is mixed C# and F#, right now my workaround solution is add a new type in F# and do mapping

**Comment by MangelMaxime** [comment]
I think I know why C# POCO was working before out of the box. 

The encoder was using converters so it was Newtonsoft doing the job for us. Because in Thoth.Json.Net v3 we decided to use the manual encoder/decoder when using `Auto` feature C# POCO has not been ported. The reason for this move is to have the same behavior (JSON output/input expectationà when using manual coders or auto coders.

**Comment by MangelMaxime** [comment]
I don't thin we are going to do anything about it in Thoth.Json.Net as this is an old issue and the next rewrite of Thoth.Json will get rid of Newtonsoft even for the .NET side.

Also, there is this blog post https://www.planetgeek.ch/2021/04/19/our-journey-to-f-json-serialization-with-a-mix-of-c-and-f/ where they explain how they have been mixing C# and F# with Newtonsoft so perhaps this can help people in the future.
